[features]
seeds = false
skip-lint = false
[programs.localnet]
perpetuals = "FUAaX8Ym86imdLvkwLjGLCGWNtFAJ6eoTtQkGwTAstF6"
[programs.devnet]
perpetuals = "FUAaX8Ym86imdLvkwLjGLCGWNtFAJ6eoTtQkGwTAstF6"
[programs.testnet]
perpetuals = "FUAaX8Ym86imdLvkwLjGLCGWNtFAJ6eoTtQkGwTAstF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/macbookpro/rust/perpetuals/keys/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
