[features]
seeds = false
skip-lint = false
[programs.localnet]
perpetuals = "BCszwEzJUvTXCKyr7ko34z6TXWv4d8Wp9gEdFcHJpfX"
[programs.devnet]
perpetuals = "BCszwEzJUvTXCKyr7ko34z6TXWv4d8Wp9gEdFcHJpfX"
[programs.testnet]
perpetuals = "BCszwEzJUvTXCKyr7ko34z6TXWv4d8Wp9gEdFcHJpfX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://testnet.dev2.eclipsenetwork.xyz"
wallet = "/Users/macbookpro/rust/perpetuals/keys/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
